apiVersion: v1
kind: Endpoints
metadata:
  name: influxdb-collectd-svc
  namespace: sa-grafana
subsets: 
  - 
    addresses:
      - ip: 172.30.234.20
    ports:
      - port: 8086
        name: influxdb
