# influxdb service
apiVersion: v1

kind: Service

metadata:
  name: sa-grafana-svc
  namespace: sa-grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: sa-grafana
