apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collectd-grafana
  namespace: sa-grafana
  labels:
    name: sa-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-grafana

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: sa-grafana
    spec:
      hostNetwork: true

      containers:
        - image: docker.io/opnfv/barometer-grafana
          name: sa-grafana
          securityContext:
            runAsUser: 0
          imagePullPolicy: Always
          env:
            - name: influxdb_host
              value: "$(SA_GRAFANA_SVC_SERVICE_HOST)"
          volumeMounts:
            - name:  influxdb-data
              mountPath:  /var/lib/influxdb/data
      volumes:
        - name:  influxdb-data
          emptyDir: {}
      restartPolicy: Always
      serviceAccount: sa-grafana
      serviceAccountName: sa-grafana
