kind: Service
apiVersion: v1
metadata:
  name: influxdb-collectd-svc
  namespace: influxdb
spec:
  type: NodePort
  ports:
    - name: collectd-svc
      protocol: UDP
      port: 25826
      targetPort: 25826
      nodePort: 30000
  selector:
    app: influxdb
  sessionAffinity: None
