kind: Service
apiVersion: v1
metadata:
  name: influxdb-svc
  namespace: influxdb
spec:
  ports:
    - name: http-svc
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: collectd-svc
      protocol: TCP
      port: 25826
      targetPort: 25826
  selector:
    app: influxdb
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
