kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ocp4x-collectd
subjects:
- kind: ServiceAccount
  name: ocp4x-collectd-sa
  namespace: ocp4x-collectd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
